Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 489
"GET /webhook HTTP/1.1" 301 0
Internal Server Error: /webhook/
Traceback (most recent call last):
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\menee\code\python\ClickPay\payments_app\views.py", line 43, in stripe_webhook
    payload, sig_header, settings.STRIPE_WEBHOOK_SECRET
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\conf\__init__.py", line 83, in __getattr__
    val = getattr(_wrapped, name)
AttributeError: 'Settings' object has no attribute 'STRIPE_WEBHOOK_SECRET'
"GET /webhook/ HTTP/1.1" 500 74582
C:\Users\menee\code\python\ClickPay\ClickPay\settings.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /webhook/
"GET /webhook/ HTTP/1.1" 400 30
Bad Request: /webhook/
"GET /webhook/ HTTP/1.1" 400 30
"GET / HTTP/1.1" 200 489
Not Found: /favicon.ico
- Broken pipe from ('127.0.0.1', 50379)
"GET /merchants/ HTTP/1.1" 200 3154
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\payments_app\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /create-payment-intent/
Traceback (most recent call last):
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\menee\code\python\ClickPay\payments_app\views.py", line 78, in create_payment_intent
    transfer_data={"destination": settings.STRIPE_ACCOUNT_ID},
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\conf\__init__.py", line 83, in __getattr__
    val = getattr(_wrapped, name)
AttributeError: 'Settings' object has no attribute 'STRIPE_ACCOUNT_ID'
"POST /create-payment-intent/ HTTP/1.1" 500 101675
Internal Server Error: /create-payment-intent/
Traceback (most recent call last):
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\rest_framework\renderers.py", line 726, in render
    template = loader.get_template(self.template)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: rest_framework/api.html
"GET /create-payment-intent/ HTTP/1.1" 500 83466
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3608
Internal Server Error: /create-payment-intent/
Traceback (most recent call last):
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\menee\code\python\ClickPay\payments_app\views.py", line 78, in create_payment_intent
    transfer_data={"destination": settings.STRIPE_ACCOUNT_ID},
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\conf\__init__.py", line 83, in __getattr__
    val = getattr(_wrapped, name)
AttributeError: 'Settings' object has no attribute 'STRIPE_ACCOUNT_ID'
"POST /create-payment-intent/ HTTP/1.1" 500 101675
C:\Users\menee\code\python\ClickPay\payments_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\payments_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\payments_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\payments_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\payments_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\payments_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\payments_app\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\payments_app\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\payments_app\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\payments_app\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\payments_app\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /payments/create-payment-intent/
"POST /payments/create-payment-intent/ HTTP/1.1" 404 3689
Not Found: /payments/create-payment-intent/
"POST /payments/create-payment-intent/ HTTP/1.1" 404 3669
C:\Users\menee\code\python\ClickPay\payments_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\ClickPay\settings.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /payments/create-payment-intent/
"POST /payments/create-payment-intent/ HTTP/1.1" 404 3669
Not Found: /payments/create-payment-intent/
"POST /payments/create-payment-intent/ HTTP/1.1" 404 3669
Not Found: /payments/create-payment-intent/
"POST /payments/create-payment-intent/ HTTP/1.1" 404 3669
Not Found: /payments/create-payment-intent/
"POST /payments/create-payment-intent/ HTTP/1.1" 404 3669
Not Found: /payments/create-payment-intent/
"POST /payments/create-payment-intent/ HTTP/1.1" 404 3689
Forbidden (CSRF cookie not set.): /
"POST / HTTP/1.1" 403 2855
Not Found: /payments_app/create-payment-intent/
"POST /payments_app/create-payment-intent/ HTTP/1.1" 404 3701
Not Found: /payments_app/create-payment-intent/
"POST /payments_app/create-payment-intent/ HTTP/1.1" 404 3701
"GET / HTTP/1.1" 200 489
"GET /static/style.css HTTP/1.1" 200 79
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3628
C:\Users\menee\code\python\ClickPay\payments_app\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /create-payment-intent/

"POST /create-payment-intent/%0A HTTP/1.1" 404 3667
Internal Server Error: /create-payment-intent/
Traceback (most recent call last):
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\menee\code\python\ClickPay\payments_app\views.py", line 35, in create_payment_intent
    return Response({
           ^^^^^^^^
NameError: name 'Response' is not defined
"POST /create-payment-intent/ HTTP/1.1" 500 103259
C:\Users\menee\code\python\ClickPay\payments_app\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /create-payment-intent/ HTTP/1.1" 201 178
"POST /create-payment-intent/ HTTP/1.1" 201 178
"POST /create-payment-intent/ HTTP/1.1" 201 178
C:\Users\menee\code\python\ClickPay\payments_app\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /merchants/ HTTP/1.1" 200 3154
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /create-stripe-account/
"GET /create-stripe-account/ HTTP/1.1" 404 3641
Bad Request: /create-payment-intent/
"POST /create-payment-intent/ HTTP/1.1" 400 86
C:\Users\menee\code\python\ClickPay\payments_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\payments_app\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\payments_app\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\payments_app\urls.py changed, reloading.
Watching for file changes with StatReloader
"OPTIONS /create-payment-intent/ HTTP/1.1" 200 180
"OPTIONS /create-payment-intent/ HTTP/1.1" 200 180
Watching for file changes with StatReloader
"OPTIONS /create-payment-intent/ HTTP/1.1" 200 0
C:\Users\menee\code\python\ClickPay\ClickPay\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\ClickPay\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\ClickPay\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\ClickPay\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\ClickPay\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\ClickPay\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\ClickPay\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\ClickPay\settings.py changed, reloading.
Watching for file changes with StatReloader
"OPTIONS /create-payment-intent/ HTTP/1.1" 200 0
"OPTIONS /create-payment-intent/ HTTP/1.1" 200 0
C:\Users\menee\code\python\ClickPay\ClickPay\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\ClickPay\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\ClickPay\settings.py changed, reloading.
Watching for file changes with StatReloader
"OPTIONS /create-payment-intent/ HTTP/1.1" 200 0
"OPTIONS /create-payment-intent/ HTTP/1.1" 200 0
C:\Users\menee\code\python\ClickPay\ClickPay\settings.py changed, reloading.
Watching for file changes with StatReloader
"OPTIONS /create-payment-intent/ HTTP/1.1" 200 0
C:\Users\menee\code\python\ClickPay\ClickPay\settings.py changed, reloading.
Watching for file changes with StatReloader
"OPTIONS /create-payment-intent/ HTTP/1.1" 200 0
Bad Request: /create-payment-intent/
"POST /create-payment-intent/ HTTP/1.1" 400 86
C:\Users\menee\code\python\ClickPay\payments_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\payments_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\payments_app\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /create-stripe-account/
Traceback (most recent call last):
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\menee\code\python\ClickPay\payments_app\views.py", line 89, in create_stripe_account
    email=request.user.email,
          ^^^^^^^^^^^^^^^^^^
AttributeError: 'AnonymousUser' object has no attribute 'email'
"GET /create-stripe-account/ HTTP/1.1" 500 100056
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3913
C:\Users\menee\code\python\ClickPay\payments_app\views.py changed, reloading.
Watching for file changes with StatReloader
Method Not Allowed: /create-payment-intent/
"GET /create-payment-intent/ HTTP/1.1" 405 40
Internal Server Error: /create-stripe-account/
Traceback (most recent call last):
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\menee\code\python\ClickPay\payments_app\views.py", line 89, in create_stripe_account
    email=request.user.email,
          ^^^^^^^^^^^^^^^^^^
AttributeError: 'AnonymousUser' object has no attribute 'email'
"GET /create-stripe-account/ HTTP/1.1" 500 98499
C:\Users\menee\code\python\ClickPay\payments_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\payments_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\ClickPay\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\payments_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\ClickPay\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\payments_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\payments_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\ClickPay\settings.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /create-stripe-account/
Traceback (most recent call last):
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\menee\code\python\ClickPay\payments_app\views.py", line 85, in create_stripe_account
    return JsonResponse({"Error: User is not authenticated"}, status=400)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\http\response.py", line 726, in __init__
    raise TypeError(
    ...<2 lines>...
    )
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
"GET /create-stripe-account/ HTTP/1.1" 500 103324
Watching for file changes with StatReloader
Internal Server Error: /create-stripe-account/
Traceback (most recent call last):
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\menee\code\python\ClickPay\payments_app\views.py", line 85, in create_stripe_account
    return JsonResponse({"Error: User is not authenticated"}, status=400)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\http\response.py", line 726, in __init__
    raise TypeError(
    ...<2 lines>...
    )
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
"GET /create-stripe-account/ HTTP/1.1" 500 103324
C:\Users\menee\code\python\ClickPay\payments_app\views.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /create-stripe-account/
"GET /create-stripe-account/ HTTP/1.1" 400 38
Bad Request: /create-stripe-account/
"GET /create-stripe-account/ HTTP/1.1" 400 38
C:\Users\menee\code\python\ClickPay\payments_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\payments_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\payments_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\customers\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\customers\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\customers\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\ClickPay\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\ClickPay\settings.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /checkout
"GET /checkout HTTP/1.1" 404 3425
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3434
C:\Users\menee\code\python\ClickPay\ClickPay\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\ClickPay\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /home_page
"GET /home_page HTTP/1.1" 404 3596
"GET /checkout HTTP/1.1" 200 294
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\urls\base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^
KeyError: 'merchants'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\menee\code\python\ClickPay\ClickPay\views.py", line 7, in home_page
    return render(request, 'home_page.html')
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\urls\base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'merchants' is not a registered namespace
"GET / HTTP/1.1" 500 117098
"GET /checkout HTTP/1.1" 200 294
"GET /checkout HTTP/1.1" 200 311
"GET /checkout HTTP/1.1" 200 323
"GET /checkout HTTP/1.1" 200 898
Not Found: /favicon.ico
- Broken pipe from ('127.0.0.1', 57292)
"GET /checkout HTTP/1.1" 200 345
"GET /checkout HTTP/1.1" 200 1022
Not Found: /create-checkout-session
"POST /create-checkout-session HTTP/1.1" 404 3639
Invalid HTTP_HOST header: '31b7-41-193-213-243.ngrok-free.app'. You may need to add '31b7-41-193-213-243.ngrok-free.app' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\utils\deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '31b7-41-193-213-243.ngrok-free.app'. You may need to add '31b7-41-193-213-243.ngrok-free.app' to ALLOWED_HOSTS.
Bad Request: /
"GET / HTTP/1.1" 400 72557
Invalid HTTP_HOST header: '31b7-41-193-213-243.ngrok-free.app'. You may need to add '31b7-41-193-213-243.ngrok-free.app' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\utils\deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '31b7-41-193-213-243.ngrok-free.app'. You may need to add '31b7-41-193-213-243.ngrok-free.app' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
"GET /favicon.ico HTTP/1.1" 400 72475
Invalid HTTP_HOST header: '31b7-41-193-213-243.ngrok-free.app'. You may need to add '31b7-41-193-213-243.ngrok-free.app' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\utils\deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '31b7-41-193-213-243.ngrok-free.app'. You may need to add '31b7-41-193-213-243.ngrok-free.app' to ALLOWED_HOSTS.
Bad Request: /checkout
"GET /checkout HTTP/1.1" 400 72644
Invalid HTTP_HOST header: '31b7-41-193-213-243.ngrok-free.app'. You may need to add '31b7-41-193-213-243.ngrok-free.app' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\utils\deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '31b7-41-193-213-243.ngrok-free.app'. You may need to add '31b7-41-193-213-243.ngrok-free.app' to ALLOWED_HOSTS.
Bad Request: /
"GET / HTTP/1.1" 400 72557
"GET /checkout HTTP/1.1" 200 1022
Not Found: /create-checkout-session
"POST /create-checkout-session HTTP/1.1" 404 3639
C:\Users\menee\code\python\ClickPay\ClickPay\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\ClickPay\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\ClickPay\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\ClickPay\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\payments_app\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\payments_app\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\payments_app\urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /create-checkout-session
"POST /create-checkout-session HTTP/1.1" 404 3639
C:\Users\menee\code\python\ClickPay\ClickPay\urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /checkout
"GET /checkout HTTP/1.1" 404 3425
C:\Users\menee\code\python\ClickPay\payments_app\urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /checkout
"GET /checkout HTTP/1.1" 404 3422
Not Found: /checkout
"GET /checkout HTTP/1.1" 404 3422
C:\Users\menee\code\python\ClickPay\payments_app\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\payments_app\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\payments_app\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\ClickPay\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /checkout HTTP/1.1" 200 1022
Internal Server Error: /create-checkout-session
Traceback (most recent call last):
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\utils\deprecation.py", line 131, in __call__
    response = self.process_response(request, response)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
    ...<9 lines>...
    )
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/create-checkout-session/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
"POST /create-checkout-session HTTP/1.1" 500 73409
C:\Users\menee\code\python\ClickPay\ClickPay\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\ClickPay\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /create-checkout-session HTTP/1.1" 301 0
Internal Server Error: /create-checkout-session/
Traceback (most recent call last):
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: create_checkout_session() missing 1 required positional argument: 'product_id'
"GET /create-checkout-session/ HTTP/1.1" 500 64611
C:\Users\menee\code\python\ClickPay\payments_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\payments_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\customers\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\payments_app\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /create-checkout-session/
Traceback (most recent call last):
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
TypeError: create_checkout_session() missing 1 required positional argument: 'product_id'
"GET /create-checkout-session/ HTTP/1.1" 500 68322
Not Found: /checkout
"GET /checkout HTTP/1.1" 404 3422
Not Found: /checkout
"GET /checkout HTTP/1.1" 404 3422
C:\Users\menee\code\python\ClickPay\ClickPay\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\payments_app\urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /payments/create-checkout-session/
Traceback (most recent call last):
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
TypeError: create_checkout_session() missing 1 required positional argument: 'product_id'
"GET /payments/create-checkout-session/ HTTP/1.1" 500 68412
C:\Users\menee\code\python\ClickPay\payments_app\urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /payments/create-checkout-session/5/
"GET /payments/create-checkout-session/5/ HTTP/1.1" 404 3552
Not Found: /payments/create-checkout-session/
"GET /payments/create-checkout-session/ HTTP/1.1" 404 3546
Watching for file changes with StatReloader
Not Found: /payments/create-checkout-session/1/
"GET /payments/create-checkout-session/1/ HTTP/1.1" 404 3552
C:\Users\menee\code\python\ClickPay\products\models.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /payments/create-checkout-session/1/
"GET /payments/create-checkout-session/1/ HTTP/1.1" 404 3552
Watching for file changes with StatReloader
Not Found: /payments/create-checkout-session/1/
"GET /payments/create-checkout-session/1/ HTTP/1.1" 404 3552
Internal Server Error: /payments/create-checkout-session/1
"GET /payments/create-checkout-session/1 HTTP/1.1" 500 46
C:\Users\menee\code\python\ClickPay\payments_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\payments_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\payments_app\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\payments_app\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\payments_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\payments_app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /payments/create-checkout-session/1 HTTP/1.1" 302 0
Not Found: /accounts/login/
"GET /accounts/login/?next=/payments/create-checkout-session/1 HTTP/1.1" 404 2833
Not Found: /checkout
"GET /checkout HTTP/1.1" 404 2771
Not Found: /create-checkout-session/
"GET /create-checkout-session/ HTTP/1.1" 404 2819
Not Found: /payments/create-checkout-session
"GET /payments/create-checkout-session HTTP/1.1" 404 3827
Not Found: /payments/create-checkout-session/
"GET /payments/create-checkout-session/ HTTP/1.1" 404 3830
Not Found: /payments/create-checkout-session
"GET /payments/create-checkout-session HTTP/1.1" 404 3827
"GET /payments/create-checkout-session/1 HTTP/1.1" 302 0
Not Found: /accounts/login/
"GET /accounts/login/?next=/payments/create-checkout-session/1 HTTP/1.1" 404 2833
Not Found: /accounts/order/1
"GET /accounts/order/1 HTTP/1.1" 404 2795
"GET /payments/order/1 HTTP/1.1" 200 932
"POST /payments/create-checkout-session/1 HTTP/1.1" 302 0
Not Found: /accounts/login/
"GET /accounts/login/?next=/payments/create-checkout-session/1 HTTP/1.1" 404 2833
C:\Users\menee\code\python\ClickPay\ClickPay\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\customers\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /payments/create-checkout-session/1 HTTP/1.1" 302 0
Not Found: /customers/login/
"GET /customers/login/?next=/payments/create-checkout-session/1 HTTP/1.1" 404 2836
C:\Users\menee\code\python\ClickPay\customers\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\customers\urls.py changed, reloading.
Watching for file changes with StatReloader
"POST /payments/create-checkout-session/1 HTTP/1.1" 302 0
Not Found: /customers/login/
"GET /customers/login/?next=/payments/create-checkout-session/1 HTTP/1.1" 404 3098
C:\Users\menee\code\python\ClickPay\customers\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\customers\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\ClickPay\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\customers\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\customers\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\customers\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /payments/create-checkout-session/1 HTTP/1.1" 302 0
Internal Server Error: /customers/login/
Traceback (most recent call last):
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\menee\code\python\ClickPay\customers\views.py", line 33, in customer_login
    return render(request, 'customers/login.html', {'error': 'Invalid email or password'})
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: customers/login.html
"GET /customers/login/?next=/payments/create-checkout-session/1 HTTP/1.1" 500 84225
C:\Users\menee\code\python\ClickPay\customers\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /payments/create-checkout-session/1 HTTP/1.1" 302 0
Internal Server Error: /customers/login/
Traceback (most recent call last):
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\menee\code\python\ClickPay\customers\views.py", line 33, in customer_login
    return render(request, 'static/customers/login.html', {'error': 'Invalid email or password'})
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: static/customers/login.html
"GET /customers/login/?next=/payments/create-checkout-session/1 HTTP/1.1" 500 84649
C:\Users\menee\code\python\ClickPay\ClickPay\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\customers\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /payments/create-checkout-session/1 HTTP/1.1" 302 0
Internal Server Error: /customers/login/
Traceback (most recent call last):
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\menee\code\python\ClickPay\customers\views.py", line 33, in customer_login
    return render(request, 'customers/login.html', {'error': 'Invalid email or password'})
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: customers/login.html
"GET /customers/login/?next=/payments/create-checkout-session/1 HTTP/1.1" 500 84481
"POST /payments/create-checkout-session/1 HTTP/1.1" 302 0
Internal Server Error: /customers/login/
Traceback (most recent call last):
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\menee\code\python\ClickPay\customers\views.py", line 33, in customer_login
    return render(request, 'customers/login.html', {'error': 'Invalid email or password'})
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'sign_up' not found. 'sign_up' is not a valid view function or pattern name.
"GET /customers/login/?next=/payments/create-checkout-session/1 HTTP/1.1" 500 117779
C:\Users\menee\code\python\ClickPay\customers\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\customers\urls.py changed, reloading.
Watching for file changes with StatReloader
"POST /payments/create-checkout-session/1 HTTP/1.1" 302 0
Internal Server Error: /customers/login/
Traceback (most recent call last):
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\menee\code\python\ClickPay\customers\views.py", line 33, in customer_login
    return render(request, 'customers/login.html', {'error': 'Invalid email or password'})
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'sign_up' not found. 'sign_up' is not a valid view function or pattern name.
"GET /customers/login/?next=/payments/create-checkout-session/1 HTTP/1.1" 500 117779
C:\Users\menee\code\python\ClickPay\customers\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\menee\code\python\ClickPay\customers\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /payments/create-checkout-session/1 HTTP/1.1" 302 0
Internal Server Error: /customers/login/
Traceback (most recent call last):
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\menee\code\python\ClickPay\customers\views.py", line 33, in customer_login
    return render(request, 'login.html', {'error': 'Invalid email or password'})
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'sign_up' not found. 'sign_up' is not a valid view function or pattern name.
"GET /customers/login/?next=/payments/create-checkout-session/1 HTTP/1.1" 500 117689
C:\Users\menee\code\python\ClickPay\customers\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /payments/order/1 HTTP/1.1" 200 932
"POST /payments/create-checkout-session/1 HTTP/1.1" 302 0
"GET /customers/login/?next=/payments/create-checkout-session/1 HTTP/1.1" 200 1072
"POST /payments/create-checkout-session/1 HTTP/1.1" 302 0
"GET /customers/login/?next=/payments/create-checkout-session/1 HTTP/1.1" 200 1072
"POST /payments/create-checkout-session/1 HTTP/1.1" 302 0
"GET /customers/login/?next=/payments/create-checkout-session/1 HTTP/1.1" 200 1072
"POST /payments/create-checkout-session/1 HTTP/1.1" 302 0
"GET /customers/login/?next=/payments/create-checkout-session/1 HTTP/1.1" 200 1072
C:\Users\menee\code\python\ClickPay\payments_app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /payments/order/1 HTTP/1.1" 200 932
C:\Users\menee\code\python\ClickPay\payments_app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /payments/order/1 HTTP/1.1" 200 1014
"GET /payments/order/1 HTTP/1.1" 200 1014
"GET /payments/order/1 HTTP/1.1" 200 1013
"GET /payments/order/1 HTTP/1.1" 200 363
"GET /customers/login/?next=/payments/create-checkout-session/1 HTTP/1.1" 200 1072
"POST /customers/login/?next=/payments/create-checkout-session/1 HTTP/1.1" 200 1072
"POST /customers/login/?next=/payments/create-checkout-session/1 HTTP/1.1" 200 1072
Internal Server Error: /customers/sign_up/
Traceback (most recent call last):
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\menee\code\python\ClickPay\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\menee\code\python\ClickPay\customers\views.py", line 19, in sign_up
    return render(request, 'registration.html', {'form': form})
                                                         ^^^^
UnboundLocalError: cannot access local variable 'form' where it is not associated with a value
"GET /customers/sign_up/ HTTP/1.1" 500 68542
